- src/Stride.CommunityToolkit/Extensions/CameraComponentExtensions.cs
- src/Stride.CommunityToolkit/Extensions/GameExtensions.cs
- src/Stride.CommunityToolkit/Extensions/GraphicsDeviceExtensions.cs
This will lead to closing NexCoreExtensions, all the functionality was added in Extensions in the Community Toolkit
Target was to get a more central approach in Stride Expansions
> Merge NexCoreExtensions into  it

- examples/code-only/CommonSettings.props
- src/Stride.CommunityToolkit/Compositing/GraphicsCompositorBuilder.cs
- src/Stride.CommunityToolkit/Extensions/AnimationComponentExtensions.cs
- src/Stride.CommunityToolkit/Extensions/CameraComponentExtensions.cs
- src/Stride.CommunityToolkit/Extensions/EntityComponentExtensions.cs
- src/Stride.CommunityToolkit/Extensions/GameExtensions.cs
- src/Stride.CommunityToolkit/Extensions/GraphicsDeviceExtensions.cs
- src/Stride.CommunityToolkit/Extensions/ModelComponentExtensions.cs
- src/Stride.CommunityToolkit/Extensions/SimulationExtensions.cs
- src/Stride.CommunityToolkit/Scripts/BasicCameraController.cs
- src/Stride.CommunityToolkit/Scripts/GameProfiler.cs
- src/Stride.CommunityToolkit/Scripts/RaySegment.cs
- src/Stride.CommunityToolkit/Skyboxes/SkyboxGenerator.cs
- src/Stride.CommunityToolkit/Skyboxes/SkyboxGeneratorContext.cs
- src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Camera Extensions from 
https://github.com/dfkeenan/StrideToolkit/blob/master/LICENSE.txt
Cleanup of usings
#16 adds to
> Add more extensions

- src/Stride.CommunityToolkit/Scripts/RaySegment.cs
Fixes Nullability and wrong docs comment
> Fix RaySegment

- docs/docfx.json
- docs/index.md
> 38 footer fix the name

- src/Stride.CommunityToolkit/Extensions/SimulationExtensions.cs
This allows the Eflag property to be accessable through the extensions if the user needs it.
> added new Eflag value to Raycast extensions

- Stride.CommunityToolkit.sln
- examples/code-only/Example05_ProceduralGeometry/Example05_ProceduralGeometry.csproj
- examples/code-only/Example05_ProceduralGeometry/Program.cs
- src/Stride.CommunityToolkit/Rendering/Utilities/IndexingType.cs
- src/Stride.CommunityToolkit/Rendering/Utilities/MeshBuilder.cs
Here is a first proposal for #47
I am not sure about the documentation section could someone assist me there maybe?
> Add mesh builder with examples

- docs/Stride.CommunityToolkit.Docs.csproj
- examples/code-only/Example01_Basic3DScene/Example01_Basic3DScene.csproj
- examples/code-only/Example01_Basic3DScene_FSharp/Example01_Basic3DScene_FSharp.fsproj
- examples/code-only/Example01_Basic3DScene_VBasic/Example01_Basic3DScene_VBasic.vbproj
- examples/code-only/Example02_GiveMeACube/Example02_GiveMeACube.csproj
- examples/code-only/Example03_StrideUI_CapsuleAndWindow/Example03_StrideUI_CapsuleAndWindow.csproj
- examples/code-only/Example04_MyraUI/Example04_MyraUI.csproj
- examples/code-only/Example05_ProceduralGeometry/Example05_ProceduralGeometry.csproj
- examples/code-only/Example_CubicleCalamity/Example_CubicleCalamity.csproj
- src/CommonSettings.props
- src/Stride.CommunityToolkit.Examples/Stride.CommunityToolkit.Examples.csproj
- src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
This just updates all refeernces from .NET to 8 and Stride to 4.2.
> Update to Stride 4.2

- examples/code-only/Example07_CubeClicker/DataSaver.cs
- examples/code-only/Example07_CubeClicker/Example07_CubeClicker.csproj
- examples/code-only/Example07_CubeClicker/GameUI.cs
- examples/code-only/Example07_CubeClicker/Program.cs
- examples/code-only/Example07_CubeClicker/Scripts/ClickHandlerComponent.cs
- examples/code-only/Example07_CubeClicker/Scripts/CubeCollector.cs
- examples/code-only/Example07_CubeClicker/Scripts/CubeData.cs
- examples/code-only/Example07_CubeClicker/Scripts/SimpleVector.cs
Adds:
1. load/delete/save the cubes 
2. updates nexvyaml ( bug with tag )
Shows:
1. Serialization of structs
2. PRoblem with "not being built in" in stride
> Add cube loading to cube clicker

- src/Stride.CommunityToolkit/Engine/GameExtensions.cs
I wanted an easier way to change FPS without having to remember the math and location to do it. This should be a lot easier for users.
> Add SetMaxFPS()

- Example08_DebugShapes/Program.cs
- Example08_DebugShapes/Scripts/ShapeUpdater.cs
- docs/manual/rendering/debug-shapes.md
- src/Stride.CommunityToolkit/Rendering/Compositing/GraphicsCompositorExtensions.cs
- src/Stride.CommunityToolkit/Rendering/DebugShapes/ImmediateDebugRenderSystem.cs
Adding some documentation for the existing method for creating debug shapes.
Added GraphicsCompsistor extension to create the renderfeature
Added docs
> Clean up and docs

- examples/code-only/Example07_CubeClicker/Core/DataSaver.cs
- examples/code-only/Example07_CubeClicker/Example07_CubeClicker.csproj
increase nexvyaml to 1.0.3
use serializeasync
> increase nexvyaml

- src/Stride.CommunityToolkit/Engine/CameraComponentExtensions.cs
adds a new world to screenpoint calculation to get a Vector2 which represents a point inside the window
> add new world to screenpoint

- examples/code-only/Example07_CubeClicker/Example07_CubeClicker.csproj
version increase from 1.0.3 to 1.1.0 for nexvyaml
> increase nexvyaml version

- src/Stride.CommunityToolkit/Module.cs
adds the module to correctly register components in the registry,
i dont know if it works , a local nuget test would be good 
but i dont know how to make it a local nuget without overthrowing the entire structure
dont merge it yet
> add module

- examples/code-only/Example_CubicleCalamity/Scripts/RaycastHandler.cs
- src/Stride.CommunityToolkit/Scripts/GizmoBillboardLetterScript.cs
replaced obsolete extensions with new ones.
> cleaned up examples

- src/Stride.CommunityToolkit/Engine/GameExtensions.cs
fixed truncated issue with SetFPS extension
added minimized fps extension
fixed FPS extension since Game inherits from IGame anyway
> added focus lost extension

- src/Stride.CommunityToolkit/Scripts/Basic3DCameraController.cs
You can toggle instructions with F2. I didn't use F1, as that is used for a profiler.
> [Input] Control instructions added for Basic3DCameraController

- examples/code-only/Example08_DebugShapes/Program.cs
- examples/code-only/Example08_DebugShapes/Scripts/ShapeUpdater.cs
- src/Stride.CommunityToolkit/Engine/GameExtensions.cs
Made a Game extension for making adding DebugShapes less cumbersome.
> Simplify Debug Shapes

- src/Stride.CommunityToolkit/Games/GameExtensions.cs
a couple extensions to make VSync access a bit simpler.
> Add vsync enabler

- src/Stride.CommunityToolkit/Engine/GameExtensions.cs
Only a *little* late but I thought I would get this easy task out of the way.
task:
https://github.com/orgs/stride3d/projects/9/views/1?pane=issue&itemId=53641619&issue=stride3d%7Cstride-community-toolkit%7C27
> feat: Simple screenshot extension

- .gitignore
- examples/code-only/Example_Bepu_Playground/Program.cs
- src/Stride.CommunityToolkit.Bepu/Engine/Primitive2DCreationOptionsWithBepu.cs
- src/Stride.CommunityToolkit.Bepu/Engine/Primitive3DCreationOptionsWithBepu.cs
- src/Stride.CommunityToolkit.Bepu/Simulation2DComponent.cs
- src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
- src/Stride.CommunityToolkit.Examples/Stride.CommunityToolkit.Examples.csproj
- src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
- src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
- src/Stride.CommunityToolkit.Windows/Stride.CommunityToolkit.Windows.csproj
- src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
- Bepu code updated to official Stride code
> chore: NuGet packages bumped

- examples/code-only/Example11_ImGui/Example11_ImGui/Properties/launchSettings.json
- src/Stride.CommunityToolkit.ImGui/ImGuiSystem.cs
- src/Stride.CommunityToolkit.ImGui/PerfMonitor.cs
- src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
Fixes #177 
We will also need to handle label IDs better in the future but this is functional for the moment.
> fix: Update imgui 224

- src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
- src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
- src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
- src/Stride.CommunityToolkit.Windows/Stride.CommunityToolkit.Windows.csproj
- src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Update to the latest Stride release
> chore: Stride updates

- Stride.CommunityToolkit.sln
- examples/code-only/Example01_Basic3DScene_MeshLine/Example01_Basic3DScene_MeshLine.csproj
- examples/code-only/Example01_Basic3DScene_MeshLine/NamespaceAnchor.cs
- examples/code-only/Example01_Basic3DScene_MeshLine/Program.cs
- examples/code-only/Example14_Raycast/Program.cs
> feat: New example added - Example01_Basic3DScene_MeshLine

- src/Stride.CommunityToolkit.Skyboxes/SkyboxGenerator.cs
Cleaned it up a bit, it crashed when I used texturesize = 64 so I just use the native size of the cubemap instead, seems to work!
> fix: Fixed and enabled skybox environment map generation

- .github/dependabot.yml
- Stride.CommunityToolkit.sln
- Added `dependabot.yml`
- Configured daily updates for NuGet packages matching the pattern "Stride.*".
> feat: Add dependabot

- src/Stride.CommunityToolkit/Scripts/Utilities/DebugTextPrinter.cs
New feature implementation for enhanced text printing functionality.
This pull request introduces a new method for printing a list of text elements and overloads the existing initialization method to accept a display position parameter. 
- `DebugTextPrinter.cs`: Added `Print(List<TextElement> textElements)` method for line-by-line text rendering.
- `DebugTextPrinter.cs`: Overloaded `Initialize(DisplayPosition startPosition)` method for flexible screen position initialization.
> feat: DebugTextPrinter - Add Print method and overload Initialize

- src/Stride.CommunityToolkit.Bepu/CameraComponentExtensions.cs
> FIX for #266

- .github/workflows/github-pages.yml
> fix: GitHub Action for Docs fixed

- .github/copilot-instructions.md
- docs/docfx.json
- docs/includes/libraries.md
- docs/index.md
- docs/manual/physics-extensions/index.md
- examples/code-only/Example01_Basic3DScene/Example01_Basic3DScene.csproj
- examples/code-only/Example07_CubeClicker/Example07_CubeClicker.csproj
- examples/code-only/Example07_CubeClicker/Program.cs
- examples/code-only/Example07_CubeClicker/Scripts/ClickHandlerComponent.cs
- examples/code-only/Example11_ImGui/Example11_ImGui.csproj
- examples/code-only/Example11_ImGui/Program.cs
- examples/code-only/Example17_SignalR/Example17_SignalR.csproj
- examples/code-only/Example17_SignalR_Blazor/Example17_SignalR_Blazor.csproj
- examples/code-only/Example_CubicleCalamity/CubeStacker.cs
- examples/code-only/Example_CubicleCalamity_BulletPhysics/CubeStacker.cs
- src/Stride.CommunityToolkit.Bepu/Bepu2DPhysicsOptions.cs
- src/Stride.CommunityToolkit.Bepu/Bepu3DPhysicsOptions.cs
- src/Stride.CommunityToolkit.Bepu/GameExtensions.cs
- src/Stride.CommunityToolkit.Bullet/Bullet2DPhysicsOptions.cs
- src/Stride.CommunityToolkit.Bullet/Bullet3DPhysicsOptions.cs
- src/Stride.CommunityToolkit.Bullet/GameExtensions.cs
- src/Stride.CommunityToolkit.Examples/Providers/ExampleProvider.cs
- src/Stride.CommunityToolkit.Examples/Providers/ExampleProvider2.cs
- src/Stride.CommunityToolkit/Engine/EntityExtensions.cs
- src/Stride.CommunityToolkit/Engine/Primitive2DEntityOptions.cs
- src/Stride.CommunityToolkit/Engine/Primitive3DEntityOptions.cs
- src/Stride.CommunityToolkit/Engine/PrimitiveEntityOptions.cs
- src/Stride.CommunityToolkit/Games/GameExtensions.cs
- src/Stride.CommunityToolkit/Scripts/Basic3DCameraController.cs
Documentation updates and code refactoring to enhance the Stride Community Toolkit's usability and transition to Bepu Physics.
This pull request significantly updates the Stride Community Toolkit by improving documentation and refactoring code to support Bepu Physics integration. Key changes include:
- `copilot-instructions.md`: Clarified guidance for GitHub Copilot and emphasized the toolkit's preview status.
- `Program.cs`: Updated game initialization and scene setup to include a graphics compositor.
- `ClickHandlerComponent.cs`: Modified to utilize the new Bepu Physics API for raycasting and entity interactions.
- `GameExtensions.cs`: Replaced old physics options with new Bepu and Bullet options for better integration.
- `CubeStacker.cs`: Enhanced entity instantiation using the new …
> refactor: Documentation updates and code refactoring

- src/Stride.CommunityToolkit/Engine/GameDefaults.cs
- src/Stride.CommunityToolkit/Engine/GameExtensions.cs
- src/Stride.CommunityToolkit/Engine/ScriptDelegateWatcher.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/Capsule2DProceduralModel.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/CircleProceduralModel.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/PolygonProceduralModel.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/Primitive2DModelType.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/Procedural2DModelBuilder.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/Procedural3DModelBuilder.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/RectangleProceduralModel.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/TriangleProceduralModel.cs
- src/Stride.CommunityToolkit/Rendering/ProceduralModels/TriangularPrismProceduralModel.cs
- Updated default ground sizes in GameDefaults.cs to improve consistency:
- Increased Default3DGroundSize to (20f).
- Increased Default2DGroundSize to (20, 0.1f, 0).
- Added `NoCameraSlotMessage` constant in GameExtensions.cs for centralized error handling.
- Improved null checks in GameExtensions.cs using ArgumentNullException.ThrowIfNull().
- Modified SetupBase2D() to remove automatic addition of 2D camera controllers.
- Introduced Add2DCameraController() and Add3DCameraController() methods for simplified camera controller attachment.
- Refactored ScriptDelegateWatcher to make ScriptComponent nullable and improve null handling.
- Removed redundant 2D model types (e.g., Circle2D, Rectangle2D) from Primitive2DModelType.
- Replaced CapsuleProceduralModel with Capsule2DProceduralModel:
- …
> refactor!: Simplify and enhance procedural models

- docs/includes/manual/examples/examples-console-app.md
- docs/index.md
- docs/manual/code-only/create-project.md
- src/Stride.CommunityToolkit.Examples/Core/ColorHelper.cs
- src/Stride.CommunityToolkit.Examples/Core/Constants.cs
- src/Stride.CommunityToolkit.Examples/Core/Example.cs
- src/Stride.CommunityToolkit.Examples/Core/ExampleProjectMeta.cs
- src/Stride.CommunityToolkit.Examples/Core/ExampleProvider.cs
- src/Stride.CommunityToolkit.Examples/Core/ProjectFileHelper.cs
- src/Stride.CommunityToolkit.Examples/Program.cs
Enhancement: Improves usability, maintainability, and functionality of the Stride Community Toolkit examples application.
This pull request refactors the codebase to enhance example discovery, improve menu display with color-coded categories, and add new commands like "Clear." It also introduces helper classes for better modularity and metadata handling.  
- **examples-console-app.md**: Updated example list with project names, categories, and added "Clear" and "Quit" commands.  
- **ExampleProvider.cs**: Refactored example discovery, added dynamic root directory location, and improved metadata handling.  
- **Program.cs**: Enhanced menu display with category labels and project names, added "Clear" command functionality.  
- **ColorHelper.cs** and **Constants.cs**: Introduced helper …
> refactor: Enhance example discovery and minor docs updates
